* How to track add source file name in one of column in dataframe?
* Answer: Using input_file_name() function and withColumn() function we can add new column for filenames.

In [0]:
df_airlines = spark.read.csv("/databricks-datasets/asa/airlines",header=True)

In [0]:
from pyspark.sql.functions import input_file_name
df_airlines = df_airlines.withColumn("FILE_NAME",input_file_name())

* Get no of rows on each file in a dataframe?
* Answer: Using input_file_name() function and groupBy transaformation we can achive no of row on each file

In [0]:
display(df_airlines.groupBy("FILE_NAME").count())

FILE_NAME,count
dbfs:/databricks-datasets/asa/airlines/2007.csv,7453215
dbfs:/databricks-datasets/asa/airlines/2008.csv,7009728
dbfs:/databricks-datasets/asa/airlines/2006.csv,7141922
dbfs:/databricks-datasets/asa/airlines/2005.csv,7140596
dbfs:/databricks-datasets/asa/airlines/2004.csv,7129270
dbfs:/databricks-datasets/asa/airlines/2003.csv,6488540
dbfs:/databricks-datasets/asa/airlines/2001.csv,5967780
dbfs:/databricks-datasets/asa/airlines/2000.csv,5683047
dbfs:/databricks-datasets/asa/airlines/1999.csv,5527884
dbfs:/databricks-datasets/asa/airlines/1997.csv,5411843
dbfs:/databricks-datasets/asa/airlines/1998.csv,5384721
dbfs:/databricks-datasets/asa/airlines/1996.csv,5351983
dbfs:/databricks-datasets/asa/airlines/1995.csv,5327435
dbfs:/databricks-datasets/asa/airlines/2002.csv,5271359
dbfs:/databricks-datasets/asa/airlines/1990.csv,5270893
dbfs:/databricks-datasets/asa/airlines/1994.csv,5180048
dbfs:/databricks-datasets/asa/airlines/1988.csv,5202096
dbfs:/databricks-datasets/asa/airlines/1992.csv,5092157
dbfs:/databricks-datasets/asa/airlines/1991.csv,5076925
dbfs:/databricks-datasets/asa/airlines/1993.csv,5070501
dbfs:/databricks-datasets/asa/airlines/1989.csv,5041200
dbfs:/databricks-datasets/asa/airlines/1987.csv,1311826